"""column for distribution creator

Revision ID: 0043_2026.01.29_d7d89670
Revises: 0042_2026.01.28_3e434625
Create Date: 2026-01-29 13:56:34.371692+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic
revision: str = "0043_2026.01.29_d7d89670"
down_revision: str | None = "0042_2026.01.28_3e434625"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("distribution", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("distribution", schema=None) as batch_op:
        batch_op.drop_column("created_by")

    # ### end Alembic commands ###
